// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/task/task.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ec2 "github.com/aproint/copilot-cli/internal/pkg/aws/ec2"
	ecs "github.com/aproint/copilot-cli/internal/pkg/aws/ecs"
	describe "github.com/aproint/copilot-cli/internal/pkg/describe"
	gomock "github.com/golang/mock/gomock"
)

// MockVPCGetter is a mock of VPCGetter interface.
type MockVPCGetter struct {
	ctrl     *gomock.Controller
	recorder *MockVPCGetterMockRecorder
}

// MockVPCGetterMockRecorder is the mock recorder for MockVPCGetter.
type MockVPCGetterMockRecorder struct {
	mock *MockVPCGetter
}

// NewMockVPCGetter creates a new mock instance.
func NewMockVPCGetter(ctrl *gomock.Controller) *MockVPCGetter {
	mock := &MockVPCGetter{ctrl: ctrl}
	mock.recorder = &MockVPCGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVPCGetter) EXPECT() *MockVPCGetterMockRecorder {
	return m.recorder
}

// SecurityGroupsWithContext mocks base method.
func (m *MockVPCGetter) SecurityGroupsWithContext(ctx context.Context, filters ...ec2.Filter) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range filters {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SecurityGroupsWithContext", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SecurityGroupsWithContext indicates an expected call of SecurityGroupsWithContext.
func (mr *MockVPCGetterMockRecorder) SecurityGroupsWithContext(ctx interface{}, filters ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, filters...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SecurityGroupsWithContext", reflect.TypeOf((*MockVPCGetter)(nil).SecurityGroupsWithContext), varargs...)
}

// SubnetIDsWithContext mocks base method.
func (m *MockVPCGetter) SubnetIDsWithContext(ctx context.Context, filters ...ec2.Filter) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range filters {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubnetIDsWithContext", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubnetIDsWithContext indicates an expected call of SubnetIDsWithContext.
func (mr *MockVPCGetterMockRecorder) SubnetIDsWithContext(ctx interface{}, filters ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, filters...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubnetIDsWithContext", reflect.TypeOf((*MockVPCGetter)(nil).SubnetIDsWithContext), varargs...)
}

// MockClusterGetter is a mock of ClusterGetter interface.
type MockClusterGetter struct {
	ctrl     *gomock.Controller
	recorder *MockClusterGetterMockRecorder
}

// MockClusterGetterMockRecorder is the mock recorder for MockClusterGetter.
type MockClusterGetterMockRecorder struct {
	mock *MockClusterGetter
}

// NewMockClusterGetter creates a new mock instance.
func NewMockClusterGetter(ctrl *gomock.Controller) *MockClusterGetter {
	mock := &MockClusterGetter{ctrl: ctrl}
	mock.recorder = &MockClusterGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterGetter) EXPECT() *MockClusterGetterMockRecorder {
	return m.recorder
}

// ClusterARNWithContext mocks base method.
func (m *MockClusterGetter) ClusterARNWithContext(ctx context.Context, app, env string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterARNWithContext", ctx, app, env)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClusterARNWithContext indicates an expected call of ClusterARNWithContext.
func (mr *MockClusterGetterMockRecorder) ClusterARNWithContext(ctx, app, env interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterARNWithContext", reflect.TypeOf((*MockClusterGetter)(nil).ClusterARNWithContext), ctx, app, env)
}

// MockDefaultClusterGetter is a mock of DefaultClusterGetter interface.
type MockDefaultClusterGetter struct {
	ctrl     *gomock.Controller
	recorder *MockDefaultClusterGetterMockRecorder
}

// MockDefaultClusterGetterMockRecorder is the mock recorder for MockDefaultClusterGetter.
type MockDefaultClusterGetterMockRecorder struct {
	mock *MockDefaultClusterGetter
}

// NewMockDefaultClusterGetter creates a new mock instance.
func NewMockDefaultClusterGetter(ctrl *gomock.Controller) *MockDefaultClusterGetter {
	mock := &MockDefaultClusterGetter{ctrl: ctrl}
	mock.recorder = &MockDefaultClusterGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDefaultClusterGetter) EXPECT() *MockDefaultClusterGetterMockRecorder {
	return m.recorder
}

// DefaultClusterWithContext mocks base method.
func (m *MockDefaultClusterGetter) DefaultClusterWithContext(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultClusterWithContext", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DefaultClusterWithContext indicates an expected call of DefaultClusterWithContext.
func (mr *MockDefaultClusterGetterMockRecorder) DefaultClusterWithContext(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultClusterWithContext", reflect.TypeOf((*MockDefaultClusterGetter)(nil).DefaultClusterWithContext), ctx)
}

// MockenvironmentDescriber is a mock of environmentDescriber interface.
type MockenvironmentDescriber struct {
	ctrl     *gomock.Controller
	recorder *MockenvironmentDescriberMockRecorder
}

// MockenvironmentDescriberMockRecorder is the mock recorder for MockenvironmentDescriber.
type MockenvironmentDescriberMockRecorder struct {
	mock *MockenvironmentDescriber
}

// NewMockenvironmentDescriber creates a new mock instance.
func NewMockenvironmentDescriber(ctrl *gomock.Controller) *MockenvironmentDescriber {
	mock := &MockenvironmentDescriber{ctrl: ctrl}
	mock.recorder = &MockenvironmentDescriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockenvironmentDescriber) EXPECT() *MockenvironmentDescriberMockRecorder {
	return m.recorder
}

// Describe mocks base method.
func (m *MockenvironmentDescriber) Describe() (*describe.EnvDescription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Describe")
	ret0, _ := ret[0].(*describe.EnvDescription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Describe indicates an expected call of Describe.
func (mr *MockenvironmentDescriberMockRecorder) Describe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Describe", reflect.TypeOf((*MockenvironmentDescriber)(nil).Describe))
}

// MockNonZeroExitCodeGetter is a mock of NonZeroExitCodeGetter interface.
type MockNonZeroExitCodeGetter struct {
	ctrl     *gomock.Controller
	recorder *MockNonZeroExitCodeGetterMockRecorder
}

// MockNonZeroExitCodeGetterMockRecorder is the mock recorder for MockNonZeroExitCodeGetter.
type MockNonZeroExitCodeGetterMockRecorder struct {
	mock *MockNonZeroExitCodeGetter
}

// NewMockNonZeroExitCodeGetter creates a new mock instance.
func NewMockNonZeroExitCodeGetter(ctrl *gomock.Controller) *MockNonZeroExitCodeGetter {
	mock := &MockNonZeroExitCodeGetter{ctrl: ctrl}
	mock.recorder = &MockNonZeroExitCodeGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNonZeroExitCodeGetter) EXPECT() *MockNonZeroExitCodeGetterMockRecorder {
	return m.recorder
}

// HasNonZeroExitCodeWithContext mocks base method.
func (m *MockNonZeroExitCodeGetter) HasNonZeroExitCodeWithContext(arg0 context.Context, arg1 []string, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasNonZeroExitCodeWithContext", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// HasNonZeroExitCodeWithContext indicates an expected call of HasNonZeroExitCodeWithContext.
func (mr *MockNonZeroExitCodeGetterMockRecorder) HasNonZeroExitCodeWithContext(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasNonZeroExitCodeWithContext", reflect.TypeOf((*MockNonZeroExitCodeGetter)(nil).HasNonZeroExitCodeWithContext), arg0, arg1, arg2)
}

// MockRunner is a mock of Runner interface.
type MockRunner struct {
	ctrl     *gomock.Controller
	recorder *MockRunnerMockRecorder
}

// MockRunnerMockRecorder is the mock recorder for MockRunner.
type MockRunnerMockRecorder struct {
	mock *MockRunner
}

// NewMockRunner creates a new mock instance.
func NewMockRunner(ctrl *gomock.Controller) *MockRunner {
	mock := &MockRunner{ctrl: ctrl}
	mock.recorder = &MockRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunner) EXPECT() *MockRunnerMockRecorder {
	return m.recorder
}

// RunTaskWithContext mocks base method.
func (m *MockRunner) RunTaskWithContext(ctx context.Context, input ecs.RunTaskInput) ([]*ecs.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTaskWithContext", ctx, input)
	ret0, _ := ret[0].([]*ecs.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunTaskWithContext indicates an expected call of RunTaskWithContext.
func (mr *MockRunnerMockRecorder) RunTaskWithContext(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTaskWithContext", reflect.TypeOf((*MockRunner)(nil).RunTaskWithContext), ctx, input)
}
