// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/aws/sessions/sessions.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	aws "github.com/aws/aws-sdk-go-v2/aws"
	gomock "github.com/golang/mock/gomock"
)

// Mockv2ConfigValidator is a mock of v2ConfigValidator interface.
type Mockv2ConfigValidator struct {
	ctrl     *gomock.Controller
	recorder *Mockv2ConfigValidatorMockRecorder
}

// Mockv2ConfigValidatorMockRecorder is the mock recorder for Mockv2ConfigValidator.
type Mockv2ConfigValidatorMockRecorder struct {
	mock *Mockv2ConfigValidator
}

// NewMockv2ConfigValidator creates a new mock instance.
func NewMockv2ConfigValidator(ctrl *gomock.Controller) *Mockv2ConfigValidator {
	mock := &Mockv2ConfigValidator{ctrl: ctrl}
	mock.recorder = &Mockv2ConfigValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockv2ConfigValidator) EXPECT() *Mockv2ConfigValidatorMockRecorder {
	return m.recorder
}

// ValidateV2Credentials mocks base method.
func (m *Mockv2ConfigValidator) ValidateV2Credentials(arg0 context.Context, arg1 aws.Config) (aws.Credentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateV2Credentials", arg0, arg1)
	ret0, _ := ret[0].(aws.Credentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateV2Credentials indicates an expected call of ValidateV2Credentials.
func (mr *Mockv2ConfigValidatorMockRecorder) ValidateV2Credentials(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateV2Credentials", reflect.TypeOf((*Mockv2ConfigValidator)(nil).ValidateV2Credentials), arg0, arg1)
}
