// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/ecs/run_task_request.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ecs "github.com/aproint/copilot-cli/internal/pkg/aws/ecs"
	gomock "github.com/golang/mock/gomock"
)

// MockECSServiceDescriber is a mock of ECSServiceDescriber interface.
type MockECSServiceDescriber struct {
	ctrl     *gomock.Controller
	recorder *MockECSServiceDescriberMockRecorder
}

// MockECSServiceDescriberMockRecorder is the mock recorder for MockECSServiceDescriber.
type MockECSServiceDescriberMockRecorder struct {
	mock *MockECSServiceDescriber
}

// NewMockECSServiceDescriber creates a new mock instance.
func NewMockECSServiceDescriber(ctrl *gomock.Controller) *MockECSServiceDescriber {
	mock := &MockECSServiceDescriber{ctrl: ctrl}
	mock.recorder = &MockECSServiceDescriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockECSServiceDescriber) EXPECT() *MockECSServiceDescriberMockRecorder {
	return m.recorder
}

// NetworkConfiguration mocks base method.
func (m *MockECSServiceDescriber) NetworkConfiguration(cluster, serviceName string) (*ecs.NetworkConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkConfiguration", cluster, serviceName)
	ret0, _ := ret[0].(*ecs.NetworkConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NetworkConfiguration indicates an expected call of NetworkConfiguration.
func (mr *MockECSServiceDescriberMockRecorder) NetworkConfiguration(cluster, serviceName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkConfiguration", reflect.TypeOf((*MockECSServiceDescriber)(nil).NetworkConfiguration), cluster, serviceName)
}

// NetworkConfigurationWithContext mocks base method.
func (m *MockECSServiceDescriber) NetworkConfigurationWithContext(ctx context.Context, cluster, serviceName string) (*ecs.NetworkConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkConfigurationWithContext", ctx, cluster, serviceName)
	ret0, _ := ret[0].(*ecs.NetworkConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NetworkConfigurationWithContext indicates an expected call of NetworkConfigurationWithContext.
func (mr *MockECSServiceDescriberMockRecorder) NetworkConfigurationWithContext(ctx, cluster, serviceName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkConfigurationWithContext", reflect.TypeOf((*MockECSServiceDescriber)(nil).NetworkConfigurationWithContext), ctx, cluster, serviceName)
}

// Service mocks base method.
func (m *MockECSServiceDescriber) Service(clusterName, serviceName string) (*ecs.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Service", clusterName, serviceName)
	ret0, _ := ret[0].(*ecs.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Service indicates an expected call of Service.
func (mr *MockECSServiceDescriberMockRecorder) Service(clusterName, serviceName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Service", reflect.TypeOf((*MockECSServiceDescriber)(nil).Service), clusterName, serviceName)
}

// ServiceWithContext mocks base method.
func (m *MockECSServiceDescriber) ServiceWithContext(ctx context.Context, clusterName, serviceName string) (*ecs.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceWithContext", ctx, clusterName, serviceName)
	ret0, _ := ret[0].(*ecs.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ServiceWithContext indicates an expected call of ServiceWithContext.
func (mr *MockECSServiceDescriberMockRecorder) ServiceWithContext(ctx, clusterName, serviceName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceWithContext", reflect.TypeOf((*MockECSServiceDescriber)(nil).ServiceWithContext), ctx, clusterName, serviceName)
}

// TaskDefinition mocks base method.
func (m *MockECSServiceDescriber) TaskDefinition(taskDefName string) (*ecs.TaskDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskDefinition", taskDefName)
	ret0, _ := ret[0].(*ecs.TaskDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TaskDefinition indicates an expected call of TaskDefinition.
func (mr *MockECSServiceDescriberMockRecorder) TaskDefinition(taskDefName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskDefinition", reflect.TypeOf((*MockECSServiceDescriber)(nil).TaskDefinition), taskDefName)
}

// TaskDefinitionWithContext mocks base method.
func (m *MockECSServiceDescriber) TaskDefinitionWithContext(ctx context.Context, taskDefName string) (*ecs.TaskDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskDefinitionWithContext", ctx, taskDefName)
	ret0, _ := ret[0].(*ecs.TaskDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TaskDefinitionWithContext indicates an expected call of TaskDefinitionWithContext.
func (mr *MockECSServiceDescriberMockRecorder) TaskDefinitionWithContext(ctx, taskDefName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskDefinitionWithContext", reflect.TypeOf((*MockECSServiceDescriber)(nil).TaskDefinitionWithContext), ctx, taskDefName)
}

// MockServiceDescriber is a mock of ServiceDescriber interface.
type MockServiceDescriber struct {
	ctrl     *gomock.Controller
	recorder *MockServiceDescriberMockRecorder
}

// MockServiceDescriberMockRecorder is the mock recorder for MockServiceDescriber.
type MockServiceDescriberMockRecorder struct {
	mock *MockServiceDescriber
}

// NewMockServiceDescriber creates a new mock instance.
func NewMockServiceDescriber(ctrl *gomock.Controller) *MockServiceDescriber {
	mock := &MockServiceDescriber{ctrl: ctrl}
	mock.recorder = &MockServiceDescriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceDescriber) EXPECT() *MockServiceDescriberMockRecorder {
	return m.recorder
}

// ClusterARN mocks base method.
func (m *MockServiceDescriber) ClusterARN(app, env string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterARN", app, env)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClusterARN indicates an expected call of ClusterARN.
func (mr *MockServiceDescriberMockRecorder) ClusterARN(app, env interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterARN", reflect.TypeOf((*MockServiceDescriber)(nil).ClusterARN), app, env)
}

// ClusterARNWithContext mocks base method.
func (m *MockServiceDescriber) ClusterARNWithContext(ctx context.Context, app, env string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterARNWithContext", ctx, app, env)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClusterARNWithContext indicates an expected call of ClusterARNWithContext.
func (mr *MockServiceDescriberMockRecorder) ClusterARNWithContext(ctx, app, env interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterARNWithContext", reflect.TypeOf((*MockServiceDescriber)(nil).ClusterARNWithContext), ctx, app, env)
}

// NetworkConfiguration mocks base method.
func (m *MockServiceDescriber) NetworkConfiguration(app, env, svc string) (*ecs.NetworkConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkConfiguration", app, env, svc)
	ret0, _ := ret[0].(*ecs.NetworkConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NetworkConfiguration indicates an expected call of NetworkConfiguration.
func (mr *MockServiceDescriberMockRecorder) NetworkConfiguration(app, env, svc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkConfiguration", reflect.TypeOf((*MockServiceDescriber)(nil).NetworkConfiguration), app, env, svc)
}

// NetworkConfigurationWithContext mocks base method.
func (m *MockServiceDescriber) NetworkConfigurationWithContext(ctx context.Context, app, env, svc string) (*ecs.NetworkConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkConfigurationWithContext", ctx, app, env, svc)
	ret0, _ := ret[0].(*ecs.NetworkConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NetworkConfigurationWithContext indicates an expected call of NetworkConfigurationWithContext.
func (mr *MockServiceDescriberMockRecorder) NetworkConfigurationWithContext(ctx, app, env, svc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkConfigurationWithContext", reflect.TypeOf((*MockServiceDescriber)(nil).NetworkConfigurationWithContext), ctx, app, env, svc)
}

// TaskDefinition mocks base method.
func (m *MockServiceDescriber) TaskDefinition(app, env, svc string) (*ecs.TaskDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskDefinition", app, env, svc)
	ret0, _ := ret[0].(*ecs.TaskDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TaskDefinition indicates an expected call of TaskDefinition.
func (mr *MockServiceDescriberMockRecorder) TaskDefinition(app, env, svc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskDefinition", reflect.TypeOf((*MockServiceDescriber)(nil).TaskDefinition), app, env, svc)
}

// TaskDefinitionWithContext mocks base method.
func (m *MockServiceDescriber) TaskDefinitionWithContext(ctx context.Context, app, env, svc string) (*ecs.TaskDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskDefinitionWithContext", ctx, app, env, svc)
	ret0, _ := ret[0].(*ecs.TaskDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TaskDefinitionWithContext indicates an expected call of TaskDefinitionWithContext.
func (mr *MockServiceDescriberMockRecorder) TaskDefinitionWithContext(ctx, app, env, svc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskDefinitionWithContext", reflect.TypeOf((*MockServiceDescriber)(nil).TaskDefinitionWithContext), ctx, app, env, svc)
}

// MockJobDescriber is a mock of JobDescriber interface.
type MockJobDescriber struct {
	ctrl     *gomock.Controller
	recorder *MockJobDescriberMockRecorder
}

// MockJobDescriberMockRecorder is the mock recorder for MockJobDescriber.
type MockJobDescriberMockRecorder struct {
	mock *MockJobDescriber
}

// NewMockJobDescriber creates a new mock instance.
func NewMockJobDescriber(ctrl *gomock.Controller) *MockJobDescriber {
	mock := &MockJobDescriber{ctrl: ctrl}
	mock.recorder = &MockJobDescriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobDescriber) EXPECT() *MockJobDescriberMockRecorder {
	return m.recorder
}

// ClusterARN mocks base method.
func (m *MockJobDescriber) ClusterARN(app, env string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterARN", app, env)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClusterARN indicates an expected call of ClusterARN.
func (mr *MockJobDescriberMockRecorder) ClusterARN(app, env interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterARN", reflect.TypeOf((*MockJobDescriber)(nil).ClusterARN), app, env)
}

// ClusterARNWithContext mocks base method.
func (m *MockJobDescriber) ClusterARNWithContext(ctx context.Context, app, env string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterARNWithContext", ctx, app, env)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClusterARNWithContext indicates an expected call of ClusterARNWithContext.
func (mr *MockJobDescriberMockRecorder) ClusterARNWithContext(ctx, app, env interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterARNWithContext", reflect.TypeOf((*MockJobDescriber)(nil).ClusterARNWithContext), ctx, app, env)
}

// NetworkConfigurationForJob mocks base method.
func (m *MockJobDescriber) NetworkConfigurationForJob(app, env, job string) (*ecs.NetworkConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkConfigurationForJob", app, env, job)
	ret0, _ := ret[0].(*ecs.NetworkConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NetworkConfigurationForJob indicates an expected call of NetworkConfigurationForJob.
func (mr *MockJobDescriberMockRecorder) NetworkConfigurationForJob(app, env, job interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkConfigurationForJob", reflect.TypeOf((*MockJobDescriber)(nil).NetworkConfigurationForJob), app, env, job)
}

// NetworkConfigurationForJobWithContext mocks base method.
func (m *MockJobDescriber) NetworkConfigurationForJobWithContext(ctx context.Context, app, env, job string) (*ecs.NetworkConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkConfigurationForJobWithContext", ctx, app, env, job)
	ret0, _ := ret[0].(*ecs.NetworkConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NetworkConfigurationForJobWithContext indicates an expected call of NetworkConfigurationForJobWithContext.
func (mr *MockJobDescriberMockRecorder) NetworkConfigurationForJobWithContext(ctx, app, env, job interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkConfigurationForJobWithContext", reflect.TypeOf((*MockJobDescriber)(nil).NetworkConfigurationForJobWithContext), ctx, app, env, job)
}

// TaskDefinition mocks base method.
func (m *MockJobDescriber) TaskDefinition(app, env, job string) (*ecs.TaskDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskDefinition", app, env, job)
	ret0, _ := ret[0].(*ecs.TaskDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TaskDefinition indicates an expected call of TaskDefinition.
func (mr *MockJobDescriberMockRecorder) TaskDefinition(app, env, job interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskDefinition", reflect.TypeOf((*MockJobDescriber)(nil).TaskDefinition), app, env, job)
}

// TaskDefinitionWithContext mocks base method.
func (m *MockJobDescriber) TaskDefinitionWithContext(ctx context.Context, app, env, job string) (*ecs.TaskDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskDefinitionWithContext", ctx, app, env, job)
	ret0, _ := ret[0].(*ecs.TaskDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TaskDefinitionWithContext indicates an expected call of TaskDefinitionWithContext.
func (mr *MockJobDescriberMockRecorder) TaskDefinitionWithContext(ctx, app, env, job interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskDefinitionWithContext", reflect.TypeOf((*MockJobDescriber)(nil).TaskDefinitionWithContext), ctx, app, env, job)
}
