// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/apprunner/apprunner.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	apprunner "github.com/aproint/copilot-cli/internal/pkg/aws/apprunner"
	resourcegroups "github.com/aproint/copilot-cli/internal/pkg/aws/resourcegroups"
	gomock "github.com/golang/mock/gomock"
)

// MockappRunnerClient is a mock of appRunnerClient interface.
type MockappRunnerClient struct {
	ctrl     *gomock.Controller
	recorder *MockappRunnerClientMockRecorder
}

// MockappRunnerClientMockRecorder is the mock recorder for MockappRunnerClient.
type MockappRunnerClientMockRecorder struct {
	mock *MockappRunnerClient
}

// NewMockappRunnerClient creates a new mock instance.
func NewMockappRunnerClient(ctrl *gomock.Controller) *MockappRunnerClient {
	mock := &MockappRunnerClient{ctrl: ctrl}
	mock.recorder = &MockappRunnerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockappRunnerClient) EXPECT() *MockappRunnerClientMockRecorder {
	return m.recorder
}

// DescribeService mocks base method.
func (m *MockappRunnerClient) DescribeService(ctx context.Context, svcARN string) (*apprunner.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeService", ctx, svcARN)
	ret0, _ := ret[0].(*apprunner.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeService indicates an expected call of DescribeService.
func (mr *MockappRunnerClientMockRecorder) DescribeService(ctx, svcARN interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeService", reflect.TypeOf((*MockappRunnerClient)(nil).DescribeService), ctx, svcARN)
}

// StartDeployment mocks base method.
func (m *MockappRunnerClient) StartDeployment(ctx context.Context, svcARN string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartDeployment", ctx, svcARN)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartDeployment indicates an expected call of StartDeployment.
func (mr *MockappRunnerClientMockRecorder) StartDeployment(ctx, svcARN interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartDeployment", reflect.TypeOf((*MockappRunnerClient)(nil).StartDeployment), ctx, svcARN)
}

// WaitForOperation mocks base method.
func (m *MockappRunnerClient) WaitForOperation(ctx context.Context, operationId, svcARN string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForOperation", ctx, operationId, svcARN)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForOperation indicates an expected call of WaitForOperation.
func (mr *MockappRunnerClientMockRecorder) WaitForOperation(ctx, operationId, svcARN interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForOperation", reflect.TypeOf((*MockappRunnerClient)(nil).WaitForOperation), ctx, operationId, svcARN)
}

// MockresourceGetter is a mock of resourceGetter interface.
type MockresourceGetter struct {
	ctrl     *gomock.Controller
	recorder *MockresourceGetterMockRecorder
}

// MockresourceGetterMockRecorder is the mock recorder for MockresourceGetter.
type MockresourceGetterMockRecorder struct {
	mock *MockresourceGetter
}

// NewMockresourceGetter creates a new mock instance.
func NewMockresourceGetter(ctrl *gomock.Controller) *MockresourceGetter {
	mock := &MockresourceGetter{ctrl: ctrl}
	mock.recorder = &MockresourceGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockresourceGetter) EXPECT() *MockresourceGetterMockRecorder {
	return m.recorder
}

// GetResourcesByTags mocks base method.
func (m *MockresourceGetter) GetResourcesByTags(ctx context.Context, resourceType string, tags map[string]string) ([]*resourcegroups.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourcesByTags", ctx, resourceType, tags)
	ret0, _ := ret[0].([]*resourcegroups.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResourcesByTags indicates an expected call of GetResourcesByTags.
func (mr *MockresourceGetterMockRecorder) GetResourcesByTags(ctx, resourceType, tags interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourcesByTags", reflect.TypeOf((*MockresourceGetter)(nil).GetResourcesByTags), ctx, resourceType, tags)
}
