// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/cli/deploy/lbws.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	elbv2 "github.com/aproint/copilot-cli/internal/pkg/aws/elbv2"
	gomock "github.com/golang/mock/gomock"
)

// MockelbGetter is a mock of elbGetter interface.
type MockelbGetter struct {
	ctrl     *gomock.Controller
	recorder *MockelbGetterMockRecorder
}

// MockelbGetterMockRecorder is the mock recorder for MockelbGetter.
type MockelbGetterMockRecorder struct {
	mock *MockelbGetter
}

// NewMockelbGetter creates a new mock instance.
func NewMockelbGetter(ctrl *gomock.Controller) *MockelbGetter {
	mock := &MockelbGetter{ctrl: ctrl}
	mock.recorder = &MockelbGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockelbGetter) EXPECT() *MockelbGetterMockRecorder {
	return m.recorder
}

// LoadBalancerWithContext mocks base method.
func (m *MockelbGetter) LoadBalancerWithContext(ctx context.Context, nameOrARN string) (*elbv2.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadBalancerWithContext", ctx, nameOrARN)
	ret0, _ := ret[0].(*elbv2.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadBalancerWithContext indicates an expected call of LoadBalancerWithContext.
func (mr *MockelbGetterMockRecorder) LoadBalancerWithContext(ctx, nameOrARN interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadBalancerWithContext", reflect.TypeOf((*MockelbGetter)(nil).LoadBalancerWithContext), ctx, nameOrARN)
}
