// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/cli/deploy/svc.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// Mockuploader is a mock of uploader interface.
type Mockuploader struct {
	ctrl     *gomock.Controller
	recorder *MockuploaderMockRecorder
}

// MockuploaderMockRecorder is the mock recorder for Mockuploader.
type MockuploaderMockRecorder struct {
	mock *Mockuploader
}

// NewMockuploader creates a new mock instance.
func NewMockuploader(ctrl *gomock.Controller) *Mockuploader {
	mock := &Mockuploader{ctrl: ctrl}
	mock.recorder = &MockuploaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockuploader) EXPECT() *MockuploaderMockRecorder {
	return m.recorder
}

// Upload mocks base method.
func (m *Mockuploader) Upload(bucket, key string, data io.Reader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", bucket, key, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockuploaderMockRecorder) Upload(bucket, key, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*Mockuploader)(nil).Upload), bucket, key, data)
}

// UploadWithContext mocks base method.
func (m *Mockuploader) UploadWithContext(ctx context.Context, bucket, key string, data io.Reader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadWithContext", ctx, bucket, key, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadWithContext indicates an expected call of UploadWithContext.
func (mr *MockuploaderMockRecorder) UploadWithContext(ctx, bucket, key, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadWithContext", reflect.TypeOf((*Mockuploader)(nil).UploadWithContext), ctx, bucket, key, data)
}

// MockversionGetter is a mock of versionGetter interface.
type MockversionGetter struct {
	ctrl     *gomock.Controller
	recorder *MockversionGetterMockRecorder
}

// MockversionGetterMockRecorder is the mock recorder for MockversionGetter.
type MockversionGetterMockRecorder struct {
	mock *MockversionGetter
}

// NewMockversionGetter creates a new mock instance.
func NewMockversionGetter(ctrl *gomock.Controller) *MockversionGetter {
	mock := &MockversionGetter{ctrl: ctrl}
	mock.recorder = &MockversionGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockversionGetter) EXPECT() *MockversionGetterMockRecorder {
	return m.recorder
}

// Version mocks base method.
func (m *MockversionGetter) Version() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Version indicates an expected call of Version.
func (mr *MockversionGetterMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockversionGetter)(nil).Version))
}

// MockserviceForceUpdater is a mock of serviceForceUpdater interface.
type MockserviceForceUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockserviceForceUpdaterMockRecorder
}

// MockserviceForceUpdaterMockRecorder is the mock recorder for MockserviceForceUpdater.
type MockserviceForceUpdaterMockRecorder struct {
	mock *MockserviceForceUpdater
}

// NewMockserviceForceUpdater creates a new mock instance.
func NewMockserviceForceUpdater(ctrl *gomock.Controller) *MockserviceForceUpdater {
	mock := &MockserviceForceUpdater{ctrl: ctrl}
	mock.recorder = &MockserviceForceUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockserviceForceUpdater) EXPECT() *MockserviceForceUpdaterMockRecorder {
	return m.recorder
}

// ForceUpdateServiceWithContext mocks base method.
func (m *MockserviceForceUpdater) ForceUpdateServiceWithContext(ctx context.Context, app, env, svc string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceUpdateServiceWithContext", ctx, app, env, svc)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForceUpdateServiceWithContext indicates an expected call of ForceUpdateServiceWithContext.
func (mr *MockserviceForceUpdaterMockRecorder) ForceUpdateServiceWithContext(ctx, app, env, svc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceUpdateServiceWithContext", reflect.TypeOf((*MockserviceForceUpdater)(nil).ForceUpdateServiceWithContext), ctx, app, env, svc)
}

// LastUpdatedAtWithContext mocks base method.
func (m *MockserviceForceUpdater) LastUpdatedAtWithContext(ctx context.Context, app, env, svc string) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastUpdatedAtWithContext", ctx, app, env, svc)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastUpdatedAtWithContext indicates an expected call of LastUpdatedAtWithContext.
func (mr *MockserviceForceUpdaterMockRecorder) LastUpdatedAtWithContext(ctx, app, env, svc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastUpdatedAtWithContext", reflect.TypeOf((*MockserviceForceUpdater)(nil).LastUpdatedAtWithContext), ctx, app, env, svc)
}

// MockaliasCertValidator is a mock of aliasCertValidator interface.
type MockaliasCertValidator struct {
	ctrl     *gomock.Controller
	recorder *MockaliasCertValidatorMockRecorder
}

// MockaliasCertValidatorMockRecorder is the mock recorder for MockaliasCertValidator.
type MockaliasCertValidatorMockRecorder struct {
	mock *MockaliasCertValidator
}

// NewMockaliasCertValidator creates a new mock instance.
func NewMockaliasCertValidator(ctrl *gomock.Controller) *MockaliasCertValidator {
	mock := &MockaliasCertValidator{ctrl: ctrl}
	mock.recorder = &MockaliasCertValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaliasCertValidator) EXPECT() *MockaliasCertValidatorMockRecorder {
	return m.recorder
}

// ValidateCertAliasesWithContext mocks base method.
func (m *MockaliasCertValidator) ValidateCertAliasesWithContext(ctx context.Context, aliases, certs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateCertAliasesWithContext", ctx, aliases, certs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateCertAliasesWithContext indicates an expected call of ValidateCertAliasesWithContext.
func (mr *MockaliasCertValidatorMockRecorder) ValidateCertAliasesWithContext(ctx, aliases, certs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCertAliasesWithContext", reflect.TypeOf((*MockaliasCertValidator)(nil).ValidateCertAliasesWithContext), ctx, aliases, certs)
}
