// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/term/selector/creds.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	aws "github.com/aws/aws-sdk-go-v2/aws"
	gomock "github.com/golang/mock/gomock"
)

// MockNames is a mock of Names interface.
type MockNames struct {
	ctrl     *gomock.Controller
	recorder *MockNamesMockRecorder
}

// MockNamesMockRecorder is the mock recorder for MockNames.
type MockNamesMockRecorder struct {
	mock *MockNames
}

// NewMockNames creates a new mock instance.
func NewMockNames(ctrl *gomock.Controller) *MockNames {
	mock := &MockNames{ctrl: ctrl}
	mock.recorder = &MockNamesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNames) EXPECT() *MockNamesMockRecorder {
	return m.recorder
}

// Names mocks base method.
func (m *MockNames) Names() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Names")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Names indicates an expected call of Names.
func (mr *MockNamesMockRecorder) Names() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Names", reflect.TypeOf((*MockNames)(nil).Names))
}

// MockSessionProvider is a mock of SessionProvider interface.
type MockSessionProvider struct {
	ctrl     *gomock.Controller
	recorder *MockSessionProviderMockRecorder
}

// MockSessionProviderMockRecorder is the mock recorder for MockSessionProvider.
type MockSessionProviderMockRecorder struct {
	mock *MockSessionProvider
}

// NewMockSessionProvider creates a new mock instance.
func NewMockSessionProvider(ctrl *gomock.Controller) *MockSessionProvider {
	mock := &MockSessionProvider{ctrl: ctrl}
	mock.recorder = &MockSessionProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionProvider) EXPECT() *MockSessionProviderMockRecorder {
	return m.recorder
}

// ConfigFromProfile mocks base method.
func (m *MockSessionProvider) ConfigFromProfile(ctx context.Context, name string) (aws.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigFromProfile", ctx, name)
	ret0, _ := ret[0].(aws.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfigFromProfile indicates an expected call of ConfigFromProfile.
func (mr *MockSessionProviderMockRecorder) ConfigFromProfile(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigFromProfile", reflect.TypeOf((*MockSessionProvider)(nil).ConfigFromProfile), ctx, name)
}

// ConfigFromStaticCreds mocks base method.
func (m *MockSessionProvider) ConfigFromStaticCreds(accessKeyID, secretAccessKey, sessionToken string) (aws.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigFromStaticCreds", accessKeyID, secretAccessKey, sessionToken)
	ret0, _ := ret[0].(aws.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfigFromStaticCreds indicates an expected call of ConfigFromStaticCreds.
func (mr *MockSessionProviderMockRecorder) ConfigFromStaticCreds(accessKeyID, secretAccessKey, sessionToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigFromStaticCreds", reflect.TypeOf((*MockSessionProvider)(nil).ConfigFromStaticCreds), accessKeyID, secretAccessKey, sessionToken)
}

// DefaultConfig mocks base method.
func (m *MockSessionProvider) DefaultConfig(ctx context.Context) (aws.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultConfig", ctx)
	ret0, _ := ret[0].(aws.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DefaultConfig indicates an expected call of DefaultConfig.
func (mr *MockSessionProviderMockRecorder) DefaultConfig(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultConfig", reflect.TypeOf((*MockSessionProvider)(nil).DefaultConfig), ctx)
}
