// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/term/selector/ec2.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ec2 "github.com/aproint/copilot-cli/internal/pkg/aws/ec2"
	gomock "github.com/golang/mock/gomock"
)

// MockVPCSubnetLister is a mock of VPCSubnetLister interface.
type MockVPCSubnetLister struct {
	ctrl     *gomock.Controller
	recorder *MockVPCSubnetListerMockRecorder
}

// MockVPCSubnetListerMockRecorder is the mock recorder for MockVPCSubnetLister.
type MockVPCSubnetListerMockRecorder struct {
	mock *MockVPCSubnetLister
}

// NewMockVPCSubnetLister creates a new mock instance.
func NewMockVPCSubnetLister(ctrl *gomock.Controller) *MockVPCSubnetLister {
	mock := &MockVPCSubnetLister{ctrl: ctrl}
	mock.recorder = &MockVPCSubnetListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVPCSubnetLister) EXPECT() *MockVPCSubnetListerMockRecorder {
	return m.recorder
}

// ListVPCSubnetsWithContext mocks base method.
func (m *MockVPCSubnetLister) ListVPCSubnetsWithContext(ctx context.Context, vpcID string) (*ec2.VPCSubnets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVPCSubnetsWithContext", ctx, vpcID)
	ret0, _ := ret[0].(*ec2.VPCSubnets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVPCSubnetsWithContext indicates an expected call of ListVPCSubnetsWithContext.
func (mr *MockVPCSubnetListerMockRecorder) ListVPCSubnetsWithContext(ctx, vpcID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVPCSubnetsWithContext", reflect.TypeOf((*MockVPCSubnetLister)(nil).ListVPCSubnetsWithContext), ctx, vpcID)
}

// ListVPCsWithContext mocks base method.
func (m *MockVPCSubnetLister) ListVPCsWithContext(ctx context.Context) ([]ec2.VPC, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVPCsWithContext", ctx)
	ret0, _ := ret[0].([]ec2.VPC)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVPCsWithContext indicates an expected call of ListVPCsWithContext.
func (mr *MockVPCSubnetListerMockRecorder) ListVPCsWithContext(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVPCsWithContext", reflect.TypeOf((*MockVPCSubnetLister)(nil).ListVPCsWithContext), ctx)
}
