name: ci

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        command: [compile-linux, compile-windows, compile-darwin]
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: .go-version

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version

      - name: Package custom resources
        run: make package-custom-resources

      - name: Build binaries
        run: make ${{matrix.command}}

      - name: Cleanup
        run: make package-custom-resources-clean

  mocks:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: .go-version

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version

      - name: Generate mocks
        run: make gen-mocks

      - name: Print out local diff after mockgen
        run: |
          git status --porcelain=v1 1>gitstatus.txt
          cat gitstatus.txt

      - name: Check for nonzero diff
        run: '[ -z "$(cat gitstatus.txt)" ] && echo "Generated mocks all match"'

  go-unit-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: .go-version

      - name: Run Go unit tests
        run: make run-unit-test

      # - name: Upload Go coverage report to Codecov
      #   uses: codecov/codecov-action@v7
      #   with:
      #     files: ./coverage.out

  js-unit-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version

      - name: Run custom resource unit tests
        run: make custom-resource-tests

      # - name: Upload Node coverage report to Codecov
      #   uses: codecov/codecov-action@v7
      #   with:
      #     directory: cf-custom-resources/

  js-lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version

      - name: Run custom resource lint
        run: make custom-resource-lint

  local-integration-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: .go-version

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version

      - name: Run local integration tests
        run: make local-integration-test

  license:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: .go-version

      - name: Run license check
        run: ./scripts/license.sh .

  conventional-commits:
    runs-on: ubuntu-24.04
    steps:
      - name: validate
        uses: actions/github-script@v9
        with:
          script: |
            // See https://gist.github.com/marcojahn/482410b728c31b221b70ea6d2c433f0c#file-conventional-commit-regex-md
            const regex = /^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([\w\-\.]+\))?(!)?: ([\w ])+([\s\S]*)/g;

            const pr = context.payload.pull_request;
            const title = pr.title;

            if (title.match(regex) == null) {
              throw `PR title "${title}"" does not match conventional commits from https://www.conventionalcommits.org/en/v1.0.0/`
            }
