name: commit

on:
  push:
    branches:
      - main
      - mainline

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: .go-version

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version

      - name: Run tests
        run: make local-test

      - name: Upload golang coverage report to Codecov
        uses: codecov/codecov-action@v7
        with:
          files: ./coverage.out

      - name: Upload node coverage report to Codecov
        uses: codecov/codecov-action@v7
        with:
          directory: cf-custom-resources/
